---
title: "Test"
author: "Zian Wang"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
library(tidyverse)
library(lhs)
library(GPfit)
```
  
```{r}
transform_input <- function(x, x_lwr, x_upr)
{
  (x - x_lwr) / (x_upr - x_lwr)
}
recover_input <- function(x, x_lwr, x_upr) {
  return(x*(x_upr - x_lwr) + x_lwr)
}

#f <- function(x1, x2, x1_lwr, x1_upr,x2_lwr, x2_upr) {
#  x1 <- recover_input(x1, x1_lwr, x1_upr)
#  x2 <- recover_input(x2, x2_lwr, x2_upr)
#  return(100*(x2-x1^2)^2 + (1-x1)^2)
#}

f <- function(x1, x2, x1_lwr, x1_upr, x2_lwr, x2_upr) {
  x1 <- recover_input(x1, x1_lwr, x1_upr)
  x2 <- recover_input(x2, x2_lwr, x2_upr)
  return(20 + (x1^2-10*cos(2*pi*x1)) + (x2^2-10*cos(2*pi*x2)))
}
```
  
```{r}
pipe <- function(ini_guess, acquisition_function, iteration, x1_lwr, x1_upr, x2_lwr, x2_upr, kappa = 2) {
  ini_guess <- ini_guess %>% mutate(x1 = transform_input(x1, x1_lwr, x1_upr)) %>% mutate(x2 = transform_input(x2, x2_lwr, x2_upr))
  ### Calculate the acquisition function value
  calculate <- function(pred_mean, pred_sd, y_best) {
    if(pred_sd == 0) {
      return(0)
    }
    else {
      value <- switch(acquisition_function,
          "Probability of improvement" = {pnorm((y_best-pred_mean)/pred_sd)},
          "Expected improvement" = {z_score <- (y_best-pred_mean)/pred_sd
                                    cdf_z <- pnorm(z_score)
                                    pred_sd*(z_score*cdf_z+dnorm(z_score))})
     return(value)
    }
  }
  
  ###
  run_acquisition <- function(my_pred, x1, x2, y_min, kappa) {
    Y_hat <- (my_pred %>% as.data.frame() %>% filter(xnew.1 == x1, xnew.2 == x2)) $ Y_hat
    MSE <- (my_pred %>% as.data.frame() %>% filter(xnew.1 == x1, xnew.2 == x2)) $ MSE
    switch(acquisition_function,
      "Confidence lower bound" = {Y_hat - kappa*sqrt(MSE)},
      {map2_dbl(Y_hat, sqrt(MSE),
                calculate, y_best = y_min)})
  }
  
  ### Initialize the data
  df_new <- expand.grid(x1 = seq(0,1, length.out = 101),
                        x2 = seq(0,1, length.out = 101),
                        KEEP.OUT.ATTRS = FALSE, 
                        stringsAsFactors = FALSE) %>% 
    as.data.frame()
  evaluation <- ini_guess %>% mutate(iteration = 0)
  acq_data <- data.frame()
  data <- data.frame()
  
  pred_list_obj <- vector(mode = 'list', length = iteration+1)
  
  ### Run the iteration
  for(t in 0:iteration) {
    ### Gaussian process
    fit <- GP_fit(
     X = evaluation %>% select(x1, x2) %>% as.matrix(),
     Y = evaluation$y,
     corr = list(type = "exponential", power = 2)
    )
    pred_from_gp <- predict.GP(fit, xnew = df_new)$complete_data %>%
      as.data.frame() %>%
      mutate(iteration = t)
    pred_list_obj[[t+1]] <- pred_from_gp
    data <- rbind(data, pred_from_gp)
    
    y_min = min(evaluation$y)
    ### Calculate the acquisition function
    temp_df <- df_new %>%
      mutate(acq_value = 
               run_acquisition(pred_from_gp, x1, x2, y_min, kappa)) %>%
      mutate(iteration = t+1)
    
    acq_data <- rbind(acq_data, temp_df)
    if(acquisition_function == "Confidence lower bound") {
      x_next <- c(df_new$x1[which.min(temp_df$acq_value)], 
                  df_new$x2[which.min(temp_df$acq_value)])
    }
    else {
      x_next <- c(df_new$x1[which.max(temp_df$acq_value)], 
                  df_new$x2[which.max(temp_df$acq_value)])
    }
    evaluation[nrow(evaluation)+1,] <- c(x_next, f(x_next[1], x_next[2], x1_lwr, x1_upr, x2_lwr, x2_upr), t+1)
  }
  ### Calculate the last iteration's data
  fit <- GP_fit(
    X = evaluation %>% select(x1, x2) %>% as.matrix(),
    Y = evaluation$y,
    corr = list(type = "exponential", power = 2)
  )
  pred_from_gp <- predict.GP(fit, xnew = df_new)$complete_data %>%
    as.data.frame() %>%
    mutate(iteration = t+1)
  data <- rbind(data, pred_from_gp)
  
  ### Recover the x1 and x2 to original space.
  evaluation <- evaluation %>% 
    mutate(x1 = recover_input(x1, x1_lwr, x1_upr)) %>%
    mutate(x2 = recover_input(x2, x2_lwr, x2_upr))
  acq_data <- acq_data %>% 
    mutate(x1 = recover_input(x1, x1_lwr, x1_upr)) %>%
    mutate(x2 = recover_input(x2, x2_lwr, x2_upr))
  
  res <- list(x1 = evaluation$x1[which.min(evaluation$y)], x2 = evaluation$x2[which.min(evaluation$y)], y = min(evaluation$y))
  
  return(list(pred_data = data, evaluation = evaluation, acq_data = acq_data, result = res))
}
```

```{r}
acq_plots <- function(acq_data, evaluation) {
  ### Acquisition function's plot
  plot_1 <- acq_data %>% ggplot() +
    geom_raster(mapping = aes(x = x1, y = x2, fill = acq_value)) +
  geom_contour(mapping = aes(x = x1, y = x2, z = acq_value),
               color = 'white') +
    geom_point(data = evaluation %>% filter(iteration > 0), 
               mapping = aes(x = x1, y = x2),
               color = "red", size = 3) +
    facet_wrap(~ iteration) +
    scale_fill_viridis_c() +
    theme_bw()
  
  print(plot_1)
}

gp_pred_mean_plot_2 <- function(pred_data, evaluation) {
  pred_data %>% 
    ggplot(mapping = aes(x = xnew.1, y = xnew.2)) +
    geom_raster(mapping = aes(fill = Y_hat)) +
    geom_point(data = evaluation, 
               mapping = aes(x = x1, y = x2), 
               shape = 0, color = "cyan") +
    coord_equal() +
    facet_wrap(~ iteration) +
    scale_fill_viridis_c(option = "E") +
    theme_bw()
}

gp_pred_sd_plot_2 <- function(pred_data, evaluation) {
  pred_data %>% 
    ggplot(mapping = aes(x = xnew.1, y = xnew.2)) +
    geom_raster(mapping = aes(fill = MSE)) +
    geom_point(data = evaluation, 
               mapping = aes(x = x1, y = x2), 
               shape = 0, color = "cyan") +
    coord_equal() +
    facet_wrap(~ iteration) +
    scale_fill_viridis_c(option = "A") +
    theme_bw()
}
```

  
```{r}
complete_process <- function(ini_n, iteration, acquisition_function) {
  x_design <- maximinLHS(n = ini_n, k = 2) %>% as.matrix() %>% as.data.frame() %>%
    purrr::set_names(c("x1", "x2"))

  ### Visualize the initial points
  x_design %>% ggplot(mapping = aes(x = x1, y = x2)) +
    geom_point() +
    coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +
    theme_bw()
  x_design <- x_design %>% 
    mutate(y = f(x1, x2, 0, 1, 0, 1))
  res <- pipe(x_design, acquisition_function, iteration, 0, 1, 0, 1)
  acq_plots(res$acq_data, res$evaluation)
  plot(gp_pred_sd_plot_2(res$pred_data, res$evaluation))
  plot(gp_pred_mean_plot_2(res$pred_data, res$evaluation))
  
  return(res)
}
```
  
```{r}
set.seed(1234)
res_1 <- complete_process(2, 10, "Expected improvement")
set.seed(1234)
res_2 <- complete_process(2, 10, "Probability of improvement")
set.seed(123)
res_3 <- complete_process(2, 5, "Confidence lower bound")
```


