---
title: "Untitled"
author: "Zian Wang"
date: "2022/2/4"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(tidyverse)

```

```{r}
library(GPfit)
```

Define the data generating function.  

```{r}
f <- function(x) {
  return((6*x-2)^2*sin(12*x-4))
}
```

```{r}
x <- seq(0, 1, by=0.0001)
y <- f(x)
graph_data <- data.frame(x = x, y = y)
graph_data %>% ggplot() +
  geom_point(mapping = aes(x = x, y = y), size = 0.01, color = "navyblue") +
  theme_bw()
```

```{r}
evaluation <- data.frame(x = c(0, 1/2, 1)) %>% 
  mutate(y = f(x))
```


```{r}
graph_data %>% 
  ggplot(mapping = aes(x = x, y = y)) +
  geom_line(size = 1.2, color = "navyblue") +
  geom_point(data = evaluation, size = 5, color = "red") +
  theme_bw()
```

```{r}
fit <- GP_fit(
  X = evaluation$x,
  Y = evaluation$y,
  corr = list(type = "exponential", power = 2)
)
```

```{r}
df_new <- data.frame(x = seq(0, 1, length.out = 101))
```

```{r}
pred_from_gp <- predict.GP(fit, xnew = df_new)
```

```{r}
df_new %>% 
  mutate(y = pred_from_gp$Y_hat, 
         y_se = sqrt(pred_from_gp$MSE)) %>%
  ggplot(mapping = aes(x = x)) +
  geom_ribbon(mapping = aes(ymin = y-2*y_se, ymax = y+2*y_se),
              fill = "navyblue", 
              alpha = 0.5) +
  geom_line(mapping = aes(y = y), color = "gold", size = 1.2) +
  geom_line(data = graph_data, mapping = aes(y = y), color = "red") +
  geom_point(data = evaluation, mapping = aes(y = y), size = 5) +
  theme_bw()
```

Probability of improvement  

```{r}
calculate_POI <- function(pred_mean, pred_sd, y_best) {
  if(pred_sd == 0) {
    return(0)
  }
  else {
    return(pnorm((y_best-pred_mean)/pred_sd))
  }
}
```



```{r}
run_probability_of_improvement <- function(df, x_new) {
  ### Fit Gaussian process
  my_gp <- GP_fit(X = df$x, Y = df$y,
                  corr = list(type = "exponential", power = 2))
  ### Make predictions
  my_pred <- predict.GP(my_gp, xnew = x_new)
  ### Current min
  y_min <- min(df$y)
  ### Iterate over predictions
  map2_dbl(my_pred$Y_hat, sqrt(my_pred$MSE),
           calculate_POI, y_best = y_min)
}
```


```{r}
df_new %>%
  mutate(POI = run_probability_of_improvement(evaluation, df_new)) %>%
  ggplot(mapping = aes(x = x, y = POI)) +
  geom_line(size = 1.2, color = "navyblue") +
  theme_bw()
```


Expected improvement  


```{r}
calculate_EI <- function(pred_mean, pred_sd, y_best) {
  if(pred_sd == 0) {
    return(0)
  }
  else {
    z_score <- (y_best-pred_mean)/pred_sd
    cdf_z <- pnorm(z_score)
    return(pred_sd*(z_score*cdf_z+dnorm(z_score)))
  }
}
```


```{r}
run_expected_improvement <- function(df, x_new) {
  ### Fit Gaussian process
  my_gp <- GP_fit(X = df$x, Y = df$y,
                  corr = list(type = "exponential", power = 2))
  ### Make predictions
  my_pred <- predict.GP(my_gp, xnew = x_new)
  ### Current min
  y_min <- min(df$y)
  ### Iterate over predictions
  map2_dbl(my_pred$Y_hat, sqrt(my_pred$MSE),
           calculate_EI, y_best = y_min)
}
```


```{r}
df_new %>%
  mutate(EI = run_expected_improvement(evaluation, df_new)) %>%
  ggplot(mapping = aes(x = x, y = EI)) +
  geom_line(size = 1.2, color = "navyblue") +
  theme_bw()
```

Confidence lower bound

```{r}
run_confidence_lower_cound <- function(df, x_new, kappa) {
  ### Fit Gaussian process
  my_gp <- GP_fit(X = df$x, Y = df$y,
                  corr = list(type = "exponential", power = 2))
  ### Make predictions
  my_pred <- predict.GP(my_gp, xnew = x_new)
  ### Calculate GP confidence lower bound
  as.numeric(my_pred$Y_hat - kappa*sqrt(my_pred$MSE))
}
```


```{r}
df_new %>%
  mutate(LB = run_confidence_lower_cound(evaluation, df_new, 2)) %>%
  ggplot(mapping = aes(x = x, y = LB)) +
  geom_line(size = 1.2, color = "navyblue") +
  theme_bw()
```


```{r}
evaluation <- data.frame(x = c(0, 1/3, 2/3, 1)) %>% 
  mutate(y = f(x))

pipe <- function(ini_guess, acquisition_function, iteration, kappa = 2) {
  ### Define the function
  f <- function(x) {
    return((6*x-2)^2*sin(12*x-4))
  }
  
  ### Calculate the acquisition function value
  calculate <- function(pred_mean, pred_sd, y_best) {
    if(pred_sd == 0) {
      return(0)
    }
    else {
      value <- switch(acquisition_function,
          "Probability of improvement" = {pnorm((y_best-pred_mean)/pred_sd)},
          "Expected improvement" = {z_score <- (y_best-pred_mean)/pred_sd
                                    cdf_z <- pnorm(z_score)
                                    pred_sd*(z_score*cdf_z+dnorm(z_score))})
     return(value)
    }
  }
  
  ###
  run_acquisition <- function(df, x_new, kappa) {
    ### Fit Gaussian process
    my_gp <- GP_fit(X = df$x, Y = df$y,
                    corr = list(type = "exponential", power = 2))
    ### Make predictions
    my_pred <- predict.GP(my_gp, xnew = x_new)
    ### Current min
    y_min <- min(df$y)
    ### Iterate over predictions
    switch(acquisition_function,
      "Confidence lower bound" = {my_pred$Y_hat - kappa*sqrt(my_pred$MSE)},
      {map2_dbl(my_pred$Y_hat, sqrt(my_pred$MSE),
                calculate, y_best = y_min)})
  }
  
  ### Initialize the data
  df_new <- data.frame(x = seq(0, 1, length.out = 10001))
  evaluation <- ini_guess %>% mutate(iteration = 0)
  acq_data <- data.frame()
  data <- data.frame()
  
  ### Run the iteration
  t <- 0
  while(t < iteration) {
    ### Gaussian process
    fit <- GP_fit(
     X = evaluation$x,
     Y = evaluation$y,
     corr = list(type = "exponential", power = 2)
    )
    pred_from_gp <- predict.GP(fit, xnew = df_new)$complete_data %>%
      as.data.frame() %>%
      mutate(iteration = t)
    data <- rbind(data, pred_from_gp)
    
    ### Calculate the acquisition function
    temp_df <- df_new %>%
      mutate(acq_value = run_acquisition(evaluation, df_new, kappa)) %>%
      mutate(iteration = t+1)
    acq_data <- rbind(acq_data, temp_df)
    if(acquisition_function == "Confidence lower bound") {
      x_next <- df_new$x[which.min(temp_df$acq_value)]
    }
    else {
      x_next <- df_new$x[which.max(temp_df$acq_value)]
    }
    evaluation[nrow(evaluation)+1,] <- c(x_next, f(x_next), t+1)
    t <- t+1
  }
  ### Calculate the last iteration's data
  fit <- GP_fit(
    X = evaluation$x,
    Y = evaluation$y,
    corr = list(type = "exponential", power = 2)
  )
  pred_from_gp <- predict.GP(fit, xnew = df_new)$complete_data %>%
    as.data.frame() %>%
    mutate(iteration = t)
  data <- rbind(data, pred_from_gp)
  
  ### Acquisition function's plot
  plot_1 <- acq_data %>%
    ggplot(mapping = aes(x = x, y = acq_value)) +
    geom_line(size = 0.5, color = "navyblue") +
    geom_vline(data = evaluation %>% filter(iteration > 0), 
               mapping = aes(xintercept = x), color = "red",
               linetype = "dashed") +
    xlab("x") +
    ylab("acquisition function value") +
    facet_wrap(~ iteration) +
    theme_bw()
  
  ### Update the plots
  point_data <- data.frame()
  t <- 0
  while(t < iteration+1) {
    point_data <- rbind(point_data, evaluation %>% 
                          filter(iteration <= t) %>%
                          mutate(iteration = t))
    t <- t+1
  }
  
  plot_2 <- data %>%
    ggplot(mapping = aes(x = xnew.1)) +
    geom_line(mapping = aes(y = Y_hat), color = "gold") +
    geom_ribbon(mapping = aes(y = Y_hat, xmin = 0, xmax = 1, 
                              ymin = Y_hat-sqrt(MSE), 
                              ymax = Y_hat+sqrt(MSE)), 
                fill = "navyblue", alpha = 0.3) +
    geom_point(data = point_data, mapping = aes(x = x, y = y),
               color = "navyblue") +
    xlab("x") +
    ylab("y hat") +
    facet_wrap(~ iteration) +
    theme_bw()
  
  ### Print the plots
  print(plot_1)
  print(plot_2)
}


pipe(evaluation, "Confidence lower bound", 10)
pipe(evaluation, "Probability of improvement", 12)
pipe(evaluation, "Expected improvement", 5)
```




